#--------------------------------------------------------------------#
# This a list of configurations to allow for training and evaluation #
#--------------------------------------------------------------------#

WANDB:
  PROJECT: 'CircleDetection'
  ENTITY: 'sdhossain'

DATA:
  ROOT_DIR: 'artifacts/data'
  REPLACE: False
  SAMPLES: 100000
  TRAIN_PROPORTION: 0.8
  VAL_PROPORTION: 0.1
  TEST_PROPORTION: 0.1
  FOLDS: 10
  IMG_SIZE: 200
  MIN_RADIUS: 5
  MAX_RADIUS: 100
  NOISE_LEVEL: 0.5

TRAIN:
  MODE: 'single'  # 'single' or 'cross-val'
  EPOCHS: 1
  BATCH_SIZE: 32
  CONTRAST_RANGE: 0
  INPUT_SHAPE: [224, 224, 3]
  OPTIMIZER: 'adam'
  LEARNING_RATE: 0.001
  ARCHITECTURE:
    BACKBONE: 'resnet18'
    FC_LAYERS: [32]
    DROPOUT: 0
    L2_REG: 0
    L2_BASE: 0
    WEIGHTS: 'imagenet'
  PREDICTIONS_DIR: 'artifacts/preds'
  CHECKPOINTS_DIR: 'artifacts/models'

EVAL:
  PREDICTIONS_CSV: 'artifacts/preds/20231122_070029_resnet18'  # <insert prediction csv path here>
  VIS_DIR: 'artifacts/visualizations'
  BACKBONE: 'resnet18'
  CHECKPOINT: null
  SALIENCY_FOCUS: 2  # 0 for row, 1 for col, 2 for radius
  INPUT_DIMS: [224, 224]


