#--------------------------------------------------------------------#
# This a list of configurations to allow for training and evaluation #
#--------------------------------------------------------------------#

DATA:
  ROOT_DIR: 'data'
  REPLACE: False
  SAMPLES: 100
  TRAIN_PROPORTION: 0.8
  VAL_PROPORTION: 0.1
  TEST_PROPORTION: 0.1
  FOLDS: 10
  IMG_SIZE: 100
  MIN_RADIUS: 10
  MAX_RADIUS: 50
  NOISE_LEVEL: 0.5

TRAIN:
  BATCH_SIZE: 32
  CONTRAST_RANGE: 0.15